# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meiju', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='subtitle',
            field=models.CharField(default='', max_length=128, verbose_name='\u5267\u96c6\u540d\u79f0'),
        ),
    ]
