# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meiju', '0003_auto_20160201_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='source',
            field=models.CharField(max_length=512, verbose_name='\u94fe\u63a5'),
        ),
    ]
